mb:
  disabled_archs: "arm32,x86"
  disabled_configs: "Coverage"
  policy: "//policy:spz_policy"
  c_version: "17"
  cxx_version: "17"

spz:
  linking_model: v3

xcode:
  deployment_target: "11.0"

zlib:
  version: "1.1.22"
  linking_model: v3
