# Libraries that only devs of your lib need should go here.

name: spz
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - boa_toolkit>=3.2.6
variables:
  PYTHONIOENCODING: utf-8
  OPENCV_IO_ENABLE_OPENEXR: 1
