# Libraries that only devs of your lib need should go here.

name: spz
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - --extra-index-url https://artifactory-uw2.adobeitc.com/artifactory/api/pypi/pypi-tech-transfer-3di-release/simple
    - --extra-index-url https://artifactory-uw2.adobeitc.com/artifactory/api/pypi/pypi-adobeshared-release/simple
    - boa_toolkit>=3.2.6
variables:
  PYTHONIOENCODING: utf-8
  OPENCV_IO_ENABLE_OPENEXR: 1
